/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Persona;
import dominio.Profesional;
import dominio.Sistema;
import dominio.TipoUsuario;
import dominio.Usuario;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author seba
 */
public class Login extends javax.swing.JPanel {

  private final JFrame ventanaPrincipal;
  private final Sistema sistema;

  /**
   * Creates new form Login
   *
   * @param ventana
   * @param sistema
   */
  public Login(JFrame ventana, Sistema sistema) {
    this.sistema = sistema;
    this.ventanaPrincipal = ventana;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtUsuario = new javax.swing.JTextField();
    lblPassword = new javax.swing.JLabel();
    lblUsuario = new javax.swing.JLabel();
    btnIngresar = new javax.swing.JButton();
    txtPassword = new javax.swing.JPasswordField();
    lblIngresoAdministrador = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 0, 102));
    jLabel1.setText("Ingresar");
    jLabel1.setName(""); // NOI18N

    txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtUsuarioKeyPressed(evt);
      }
    });

    lblPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    lblPassword.setLabelFor(txtPassword);
    lblPassword.setText("Contraseña");
    lblPassword.setName(""); // NOI18N

    lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    lblUsuario.setLabelFor(txtUsuario);
    lblUsuario.setText("Usuario");
    lblUsuario.setName(""); // NOI18N

    btnIngresar.setBackground(new java.awt.Color(255, 0, 102));
    btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
    btnIngresar.setText("Ingresar");
    btnIngresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIngresarActionPerformed(evt);
      }
    });

    txtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtPasswordKeyPressed(evt);
      }
    });

    lblIngresoAdministrador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    lblIngresoAdministrador.setForeground(new java.awt.Color(255, 0, 102));
    lblIngresoAdministrador.setText("Ingresar como administrador");
    lblIngresoAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    lblIngresoAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lblIngresoAdministradorMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(100, 100, 100)
            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(100, 100, 100)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lblPassword)
              .addComponent(txtUsuario)
              .addComponent(txtPassword)
              .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lblIngresoAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(183, 183, 183)
            .addComponent(jLabel1)))
        .addContainerGap(108, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(lblUsuario)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblPassword)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34)
        .addComponent(btnIngresar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
        .addComponent(lblIngresoAdministrador)
        .addContainerGap())
    );

    jLabel1.getAccessibleContext().setAccessibleName("lblLoginTitulo");
    txtUsuario.getAccessibleContext().setAccessibleName("txtUsuario");
    lblPassword.getAccessibleContext().setAccessibleName("lblPassword");
    lblUsuario.getAccessibleContext().setAccessibleName("lblUsuario");
    btnIngresar.getAccessibleContext().setAccessibleName("btnIngresar");
  }// </editor-fold>//GEN-END:initComponents

  private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    procesarLogin();
  }//GEN-LAST:event_btnIngresarActionPerformed

  private void lblIngresoAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIngresoAdministradorMouseClicked
    // TODO add your handling code here:
    ventanaPrincipal.remove(this);
    new InterfazBotonesAdministrador(sistema, ventanaPrincipal);
    ventanaPrincipal.pack();
    ventanaPrincipal.setLocationRelativeTo(null);
  }//GEN-LAST:event_lblIngresoAdministradorMouseClicked

  private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      procesarLogin();
    }
  }//GEN-LAST:event_txtPasswordKeyPressed

  private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      procesarLogin();
    }
  }//GEN-LAST:event_txtUsuarioKeyPressed

  private void procesarLogin() {
    String nombreUsuario = txtUsuario.getText();
    char[] passwordArray = txtPassword.getPassword();
    String password = "";

    for (int i = 0; i < passwordArray.length; i++) {
      password += passwordArray[i];
    }

    Persona persona = sistema.obtenerUsuario(nombreUsuario, password);

    if (persona != null) {
      sistema.setUsuarioLogueado(persona);
      TipoUsuario tipoUsuario = persona.getTipo();
      sistema.setUsuarioActivo(tipoUsuario);
      ventanaPrincipal.remove(this);

      switch (tipoUsuario) {
        case USUARIO:
          new InterfazBotonesUsuario(sistema, ventanaPrincipal, (Usuario) persona);
          break;
        case PROFESIONAL:
          new InterfazBotonesProfesional(sistema, ventanaPrincipal, (Profesional) persona);
          break;
      }
      ventanaPrincipal.pack();
      ventanaPrincipal.setLocationRelativeTo(null);
    } else {
      JOptionPane.showMessageDialog(this,
          "Verifique sus credenciales e intente nuevamente",
          "Error al ingresar",
          JOptionPane.ERROR_MESSAGE);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnIngresar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel lblIngresoAdministrador;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblUsuario;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtUsuario;
  // End of variables declaration//GEN-END:variables
}
